### ISSUE TITLE
Live GeoJSON Endpoint for Neighborhoods

### ISSUE THREAD

**Issue by gavinr** [AvidDabbler/STL-GeoJson-Data#1]
If [this item](https://www.arcgis.com/home/item.html?id=49a5a4e8826f4289b9204d551ecd6e5a) is maintained (I think it is, but would like to confirm), then a live GeoJSON feed of this would be:

https://services6.arcgis.com/HZXbCkpCSqbGd0vK/arcgis/rest/services/neighborhoods_rev/FeatureServer/0/query?where=1%3D1&&f=pgeojson

See it live: http://geojson.io/#data=data:text/x-url,https%3A%2F%2Fservices6.arcgis.com%2FHZXbCkpCSqbGd0vK%2Farcgis%2Frest%2Fservices%2Fneighborhoods_rev%2FFeatureServer%2F0%2Fquery%3Fwhere%3D1%253D1%26%26f%3Dpgeojson

**Comment by AvidDabbler** [comment]
This is nice. I think the issue that I take with it is that this isn't linked on the site and registered under a user. I am afraid if they leave or it it gets deleted it won't be accessible.
